[package]
name = "leviticus"
description = "Leviticus is a suite of tools which help developers build robust and maintainable applications across platforms, languages, frameworks, and runtimes."
edition = "2024"
version = "0.0.1"
authors = ["Loi Tran"]
license = "MIT OR Apache-2.0"

documentation = "https://docs.rs/leviticus"
homepage = "https://kb-blog-primetimetran.vercel.app/"
repository = "https://github.com/primetimetran/leviticus"
keywords = ["virtualization","visualization","filesystem", "development-tools", "os"]
categories = ["virtualization","visualization","filesystem", "development-tools", "os"]

[dependencies]
# Local path dependencies stay as they are
cli = { path = "../cli" }

# Inherited dependencies
dirs = { workspace = true }
toml = { workspace = true }
libc = { workspace = true }
fuser = { workspace = true }
notify = { workspace = true }
tracing = { workspace = true }
sd-notify = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
